spring:
  application:
    name: london-discovery
  security:
    user:
      name: ${EUREKA_USER_NAME:admin}
      password: ${EUREKA_USER_PASSWORD:password}
    
server:
  port: ${PORT:5000}
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/